import os
import subprocess
from github import Github
from api.settings import settings


def get_github_client() -> Github:
    return Github(settings.GITHUB_TOKEN)


def clone_repo(repo_url: str, dest_path: str, branch: str = "") -> str:
    """Clone a repository to dest_path. Returns the cloned path."""
    cmd = ["git", "clone", "--depth", "1"]
    if branch:
        cmd += ["--branch", branch]
    cmd += [repo_url, dest_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"Clone failed: {result.stderr}")
    return dest_path


def create_branch(repo_full_name: str, branch_name: str, from_branch: str = "") -> str:
    """Create a new branch on GitHub."""
    g = get_github_client()
    repo = g.get_repo(repo_full_name)
    base_branch = from_branch or repo.default_branch
    sha = repo.get_branch(base_branch).commit.sha
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sha)
    return branch_name


def push_branch(repo_path: str, repo_url: str, branch: str, token: str) -> None:
    """Push a branch to remote with token auth."""
    authenticated_url = repo_url.replace("https://", f"https://{token}@")
    subprocess.run(
        ["git", "push", authenticated_url, f"HEAD:{branch}", "--force"],
        cwd=repo_path,
        check=True,
        capture_output=True,
    )


def create_pr(repo_full_name: str, branch: str, task) -> str:
    """Create a pull request and return the PR URL."""
    g = get_github_client()
    repo = g.get_repo(repo_full_name)
    pr = repo.create_pull(
        title=f"[bc-agent] {task.goal[:72]}",
        body=_render_pr_body(task),
        head=branch,
        base=repo.default_branch,
    )
    return pr.html_url


def _render_pr_body(task) -> str:
    lines = [
        "## BC-Agentic Automated PR",
        "",
        f"**Task:** {task.goal}",
        f"**Task ID:** {task.id}",
        f"**Model:** {task.model_used}",
        f"**Token usage:** {task.token_usage}",
        "",
        "---",
        "*Generated by [BC-Agentic](https://github.com/breakingcircuits1337/fun-factory)*",
    ]
    return "\n".join(lines)


def get_repo_full_name(repo_url: str) -> str:
    """Extract owner/repo from GitHub URL."""
    url = repo_url.rstrip("/").rstrip(".git")
    parts = url.split("/")
    if len(parts) >= 2:
        return f"{parts[-2]}/{parts[-1]}"
    return ""


def get_diff(repo_path: str) -> str:
    """Get the current git diff in the repo."""
    result = subprocess.run(
        ["git", "diff", "HEAD~1", "HEAD"],
        cwd=repo_path,
        capture_output=True,
        text=True,
    )
    return result.stdout or ""
